export enum ExitCode {
    SUCCESS = 0,
    SUCCEEDED_WITH_FIXES = 20,
    COMMAND_ERROR = 80,
    SERVER_ERROR = 99,
    SERVER_TIMEOUT_ERROR = 300,
    INVALID_ARGUMENTS = 103,
    FAILED_SCAN = 800,
}
