export enum ExitCode {
    SUCCESS = 0,
    INVALID_CONFIG_FILE = 10,
    MISSING_SEARCH_PATTERN = 11,
    NO_TEMPLATES_FOUND = 12,
    NO_POLICIES_FOUND = 13,
    INVALID_TEMPLATE = 14,
    VIOLATIONS_FOUND = 20,
    SIDE_EFFECTS_FAILED = 30,
    SERVER_ERROR = 99,
}