name: CODEOWNERS Checker

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/CODEOWNERS

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mszostok/codeowners-validator@v0.7.4
      with:
        checks: "duppatterns,syntax"
        experimental_checks: "notowned,avoid-shadowing"
