name: Gomboc.ai CloudFormation CLI Build

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs:
  simple-test:
    name: Simple Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build tar ball
        id: build-tar-ball
        run: | 
          npm i
          npm run build
          npm ci
          
      - name: Install globally and test package
        shell: bash
        run: | 
          npm install -g .
          echo $(gomboc-cfn --help) 
