# Build container and perform health check
name: Build and push

permissions:
  contents: read
  id-token: write # for AWS Assume Role
  packages: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' }}
          tags: gombocai/cli:latest

      - name: run structure tests
        uses: plexsystems/container-structure-test-action@v0.1.0
        with:
          image: gombocai/cli:latest
          config: test/container-structure-test.yaml
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'gombocai/cli:latest'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'