# Build container and perform health check
name: Skaffold Pipeline

permissions:
  contents: read
  id-token: write # for AWS Assume Role
  packages: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
env:
  AWS_REGION: 'us-east-1'
  AWS_ACCOUNT_BUILD: '255036831885'

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials Read Write ECR
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_BUILD }}:role/GitHub-ReadWrite-CLI
          mask-aws-account-id: 'false'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create tarz
        id: create-tarz
        run: |
          npm run build
          npm pack

      - name: Docker build
        id: docker-build
        run: |
          docker build -t gomboc-cli .
          docker tag gomboc-cli:latest ${{ env.AWS_ACCOUNT_BUILD }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/cli:latest
          docker push aws_account_id.dkr.ecr.us-west-2.amazonaws.com/my-repository:tag