name: Node.js Package

permissions:
  id-token: write
  contents: read

on:
  release:
    types: [created]

jobs:
  pull-schema:
    uses: Gomboc-AI/ReusableWorkflows/.github/workflows/pullGraphqlSchema.yml@main
    with:
      ECR_SERVICE: ${{ vars.AWS_ECR_REPO_SCANAPI }}
      ROLE_SERVICE: ${{ github.event.repository.name=='cli' && 'cli' || 'cli-dev' }}

  publish:
    needs: pull-schema
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.20.0
          registry-url: 'https://npm.pkg.github.com'
          scope: '@Gomboc-AI'

      - uses: actions/download-artifact@v3
        with:
          name: graphql-schema
      
      - name: Generate types
        run: |
          npm install -g apollo
          npm install -g graphql
          apollo codegen:generate --localSchemaFile=schema.graphql --target=typescript --tagName=gql --queries='src/apiclient/*.ts' --globalTypesFile='src/apiclient/__generated__/GlobalTypes.ts'

      - name: Build, lint and install CLI
        run: |
          npm i
          npm run build
          
      - run: npm ci

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.DEFAULT_AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_BUILD }}:role/GitHub-ReadWrite-cli
          mask-aws-account-id: "true"

      - name: Build Tar File and upload to S3
        run: |
          mkdir pack
          npm pack --pack-destination pack/
          cd pack
          mv * cli.tar
          aws s3 cp cli.tar s3://gombocdownloads/cli.tar
