name: Node.js Package

permissions:
  id-token: write
  contents: read

on:
  release:
    types: [created]

jobs:
  pull-schema:
    uses: Gomboc-AI/ReusableWorkflows/.github/workflows/pullGraphqlSchema.yml@main
    with:
      ECR_SERVICE: 'scanapi'
      ROLE_SERVICE: ${{ github.event.repository.name }}

  publish:
    needs: pull-schema
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@Gomboc-AI'

      - uses: actions/download-artifact@v3
        with:
          name: graphql-schema
      
      - name: Generate types
        run: |
          npm install -g apollo
          npm install -g graphql
          apollo codegen:generate --localSchemaFile=schema.graphql --target=typescript --tagName=gql --queries='src/apiclient/*.ts' --globalTypesFile='src/apiclient/__generated__/GlobalTypes.ts'

      - name: Build, lint and install CLI
        run: npm run build
          
      - run: npm ci

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
